### PR TITLE
Few of the other string metric algorithms from RockyMaddens scala library

### PR DESCRIPTION
**Pull request by hashd**
Implementation of the following string metric algorithms and corresponding tests:
- DiceSorensenMetric
- HammingDistance
- JaccardSimilarityMetric
- LevenshteinDistance
- NGramSimilarityMetric
- WeightedLevenshteinDistance

Added dogma for code linting as dependency

### CODE REVIEW

**Comment by hashd** [comment]
I wanted fuzzy string matching in Elixir for another application I was working on and came across your library. Thought I could help you implement few of the other algorithms implemented in RockyMadden's scala library.

I have also added dogma as a dependency for code linting

**Comment by smashedtoatoms** [comment]
This is great.  Thanks a lot.  Adding dogma was a great idea as well.

**Comment by smashedtoatoms** [comment]
I updated hex and the docs.  We should be all set.  Let me know if I missed something.  Thanks again.

**Comment by hashd** [comment]
I have a partial implementation of Ratcliff Obershelp algorithm, need to complete it and write tests against it. Will create a PR sometime soon.

Thanks for merging and including me in the list of contributors in quick time.

I wish Dogma rules were configurable per project.

**Comment by smashedtoatoms** [comment]
I added you as a collaborator so that you can just merge things in yourself.  I really appreciate the help.

**Pull request merged**
